### ISSUE TITLE
Any reason this hasn't been submitted to borisyankov/DefinitelyTyped?

### ISSUE THREAD

**Issue by elisee** [clark-stevenson/p2.d.ts#1]
Hey! Thanks for writing this definition file.

I was wondering if there's a reason you haven't submitted it as a pull request to https://github.com/borisyankov/DefinitelyTyped/? Would be nice to be able to use it with `tsd`.

**Comment by clark-stevenson** [comment]
Hey mate, thanks! They may be a little outdated, updating is on my todo. 

Feel free to push these to DT if it helps for sure, they are only a few months outdated!

I will go on to maintain my own definitions atleast until some final 1.0 release. It is not to be awkward, it is just I spent ages undoing bad commits a couple of years ago, and then having arguments about tests and stuff like that.  

Here I have no issues or real tests for better or worse.

**Comment by clark-stevenson** [comment]
This is merged by DT.  Thanks to @apare for making it possible.
