### ISSUE TITLE
How to use this with nodejs?

### ISSUE THREAD

**Issue by piranha771** [clark-stevenson/p2.d.ts#3]
I've, downloaded the p2 package via npm for nodejs.
How do I use the p2.d.ts with this package? Can you give an example?

``` javascript
/// <reference path='../typings/p2/p2.d.ts' />
import p2 = require('p2'); // <---- this causes 'p2 module not found' error (TS2307)
import GameObject = require('./GameObjectNew');
import player = require('./asset/PlayerNew');


class Game {

    gameObjects: GameObject[] = [];
    players: GameObject[] = [];
    sessionEvents = [];
    globalEvents = [];

    world: p2.World = new p2.World({
        gravity: [0.0, 0.0]
    });

.........
```

**Comment by clark-stevenson** [comment]
I personally cannot speak for require as I use SystemJS (but even then, I do not use SystemJS with p2). 

I would guess that the following line may need to be added to at the bottom of the p2.d.ts file. Can you try it?

declare module 'p2' {
    export = p2;
}

That might fix your p2 error.  If you are using ES6 or a new version of typescript, I think it needs to be

declare module 'p2' {
   export default p2;
}

But a lot of this is guesswork.  All my projects still use the trusty script tag apart from one project which I am working on in my free time with SystemJS.... I hope someone else may be able to chip in if this does not work.

**Comment by piranha771** [comment]
Thanks a lot, that works like a charm!
